# Generated by Django 5.0.6 on 2026-08-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical'), ('travel', 'Travel'), ('booking', 'Booking'), ('ai', 'AI Agents'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
